/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON = 1,
  anon_sym_EQ_EQ_EQ_EQ_EQ = 2,
  anon_sym_LF = 3,
  anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON = 4,
  sym_file_path = 5,
  sym_blank_lines = 6,
  sym_body_line = 7,
  sym_source_file = 8,
  sym_file_block = 9,
  sym_file_header = 10,
  sym_file_end = 11,
  sym_file_body = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_file_body_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON] = "===== FILE: ",
  [anon_sym_EQ_EQ_EQ_EQ_EQ] = " =====",
  [anon_sym_LF] = "\n",
  [anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON] = "===== END FILE: ",
  [sym_file_path] = "file_path",
  [sym_blank_lines] = "blank_lines",
  [sym_body_line] = "body_line",
  [sym_source_file] = "source_file",
  [sym_file_block] = "file_block",
  [sym_file_header] = "file_header",
  [sym_file_end] = "file_end",
  [sym_file_body] = "file_body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_file_body_repeat1] = "file_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON] = anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
  [anon_sym_EQ_EQ_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ_EQ_EQ,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON] = anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON,
  [sym_file_path] = sym_file_path,
  [sym_blank_lines] = sym_blank_lines,
  [sym_body_line] = sym_body_line,
  [sym_source_file] = sym_source_file,
  [sym_file_block] = sym_file_block,
  [sym_file_header] = sym_file_header,
  [sym_file_end] = sym_file_end,
  [sym_file_body] = sym_file_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_file_body_repeat1] = aux_sym_file_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_lines] = {
    .visible = true,
    .named = true,
  },
  [sym_body_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_file_block] = {
    .visible = true,
    .named = true,
  },
  [sym_file_header] = {
    .visible = true,
    .named = true,
  },
  [sym_file_end] = {
    .visible = true,
    .named = true,
  },
  [sym_file_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_path = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_path] = "path",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      if (lookahead == '\t') SKIP(0);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == '\t') SKIP(1);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\t') SKIP(1);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(3);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'D') ADVANCE(4);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead == 'F') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(8);
      END_STATE();
    case 21:
      if (lookahead == 'F') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'I') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'L') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == 'L') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'N') ADVANCE(17);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '=') ADVANCE(35);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ_EQ_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '=') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '=') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_blank_lines);
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 28, .external_lex_state = 1},
  [4] = {.lex_state = 28},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28, .external_lex_state = 1},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28, .external_lex_state = 1},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28, .external_lex_state = 1},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 27},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 27},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ_EQ_EQ] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_body_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym_file_block] = STATE(2),
    [sym_file_header] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_file_header,
    STATE(4), 2,
      sym_file_block,
      aux_sym_source_file_repeat1,
  [14] = 5,
    ACTIONS(9), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON,
    ACTIONS(11), 1,
      sym_body_line,
    STATE(5), 1,
      sym_file_end,
    STATE(6), 1,
      aux_sym_file_body_repeat1,
    STATE(10), 1,
      sym_file_body,
  [30] = 4,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
    STATE(3), 1,
      sym_file_header,
    STATE(4), 2,
      sym_file_block,
      aux_sym_source_file_repeat1,
  [44] = 2,
    ACTIONS(20), 1,
      sym_blank_lines,
    ACTIONS(18), 2,
      ts_builtin_sym_end,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
  [52] = 3,
    ACTIONS(22), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON,
    ACTIONS(24), 1,
      sym_body_line,
    STATE(8), 1,
      aux_sym_file_body_repeat1,
  [62] = 2,
    ACTIONS(28), 1,
      sym_blank_lines,
    ACTIONS(26), 2,
      ts_builtin_sym_end,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
  [70] = 3,
    ACTIONS(30), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON,
    ACTIONS(32), 1,
      sym_body_line,
    STATE(8), 1,
      aux_sym_file_body_repeat1,
  [80] = 1,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
      sym_blank_lines,
  [86] = 2,
    ACTIONS(9), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON,
    STATE(7), 1,
      sym_file_end,
  [93] = 1,
    ACTIONS(26), 2,
      ts_builtin_sym_end,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
  [98] = 1,
    ACTIONS(37), 2,
      sym_body_line,
      anon_sym_EQ_EQ_EQ_EQ_EQENDFILE_COLON,
  [103] = 1,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      anon_sym_EQ_EQ_EQ_EQ_EQFILE_COLON,
  [108] = 1,
    ACTIONS(41), 1,
      sym_file_path,
  [112] = 1,
    ACTIONS(43), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQ,
  [116] = 1,
    ACTIONS(45), 1,
      sym_file_path,
  [120] = 1,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
  [124] = 1,
    ACTIONS(49), 1,
      anon_sym_EQ_EQ_EQ_EQ_EQ,
  [128] = 1,
    ACTIONS(51), 1,
      anon_sym_LF,
  [132] = 1,
    ACTIONS(53), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 44,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 62,
  [SMALL_STATE(8)] = 70,
  [SMALL_STATE(9)] = 80,
  [SMALL_STATE(10)] = 86,
  [SMALL_STATE(11)] = 93,
  [SMALL_STATE(12)] = 98,
  [SMALL_STATE(13)] = 103,
  [SMALL_STATE(14)] = 108,
  [SMALL_STATE(15)] = 112,
  [SMALL_STATE(16)] = 116,
  [SMALL_STATE(17)] = 120,
  [SMALL_STATE(18)] = 124,
  [SMALL_STATE(19)] = 128,
  [SMALL_STATE(20)] = 132,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_block, 2, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_body, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_block, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_body_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_end, 4, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_header, 4, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_block, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [47] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_body_line = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_body_line] = sym_body_line,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_body_line] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tcatdump_external_scanner_create(void);
void tree_sitter_tcatdump_external_scanner_destroy(void *);
bool tree_sitter_tcatdump_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tcatdump_external_scanner_serialize(void *, char *);
void tree_sitter_tcatdump_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tcatdump(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tcatdump_external_scanner_create,
      tree_sitter_tcatdump_external_scanner_destroy,
      tree_sitter_tcatdump_external_scanner_scan,
      tree_sitter_tcatdump_external_scanner_serialize,
      tree_sitter_tcatdump_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "tcatdump",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
